from lib import write
S40 = [
    {"item": "coolant", "action": "replace"},
    {"item": "brake_fluid", "action": "replace"},
    {"item": "transmission_oil", "action": "replace", "note": "שמן תיבת ההפחתה של מנוע ההנעה"},
    {"item": "cabin_filter", "action": "replace"},
    {"item": "washer_fluid", "action": "inspect", "note": "השלמה"},
    {"item": "hybrid_system", "action": "inspect", "note": "סוללת ההנעה, רתמות מתח גבוה ונמוך של הסוללה ומנוע ההנעה, ברגי קיבוע מנוע ההנעה"},
    {"item": "electrical_system", "action": "inspect", "note": "שקע טעינה מהירה/איטית, חלונות חשמליים, מערכת שמע, מצלמות ומכ\"מים, מראות חשמליות, כיוון מושבים"},
    {"item": "battery_12v", "action": "inspect", "note": "מתח המצבר והדקים"},
    {"item": "ac_system", "action": "inspect", "note": "מיזוג קר/חם, רתמות מתח של המדחס ושל מחמם ה-PTC"},
    {"item": "diagnostics", "action": "inspect", "note": "בדיקת יחידת T-BOX ועדכוני תוכנה"},
    {"item": "lights", "action": "inspect"},
    {"item": "wipers", "action": "inspect", "note": "מגבים קדמי ואחורי"},
    {"item": "door_hinges", "action": "inspect", "note": "פתיחה/סגירה של דלתות וגג נפתח, שלט מפתח"},
    {"item": "tires", "action": "inspect", "note": "צמיגים, אומים ולחץ אוויר (השלמת לחץ)"},
    {"item": "brake_pads", "action": "inspect", "note": "בדיקת בלמים בלי פירוק גלגלים; החלפה לפי מצב"},
    {"item": "brake_lines", "action": "inspect", "note": "צינורות בלם ומיכל נוזל הבלמים"},
    {"item": "body_underside", "action": "inspect", "note": "ברגים ואומים של השלדה"},
    {"item": "cv_boots", "action": "inspect", "note": "שרוולים/כיסויי גומי בשלדה"},
    {"item": "steering", "action": "inspect"},
    {"item": "seat_belts", "action": "inspect", "note": "קדמיות ואחוריות"},
]
write(dict(
    id="skywell-et5-2021-2025-ev", make="Skywell", make_he="סקיוול", model="ET5", model_he="ET5", generation="ET5",
    years=[2021, 2025], engines=["EV (TZ200XSJ)"], fuel="electric", importer="המאגר ב.נ.כ בע\"מ",
    interval={"km": 40000, "months": 24, "note": "לפי חוברת השירות והאחריות של היבואן: ביקורת ראשונית ללא עלות ב-5,000 ק\"מ או 6 חודשים, ואחריה טיפול כל 40,000 ק\"מ או 24 חודשים"},
    cycle_km=40000,
    services=[{"km": 40000, "items": S40}],
    long_interval=[
        {"item": "cabin_filter", "action": "replace", "every_km": 20000, "every_months": 12,
         "note": "הערת הטבלה: מסנן המזגן מוחלף כל 12 חודשים או 20,000 ק\"מ (בתדירות גבוהה מהטיפול הדו-שנתי)"},
        {"item": "tire_rotation", "action": "rotate", "every_km": 10000,
         "note": "ספר הנהג ממליץ על סבב צמיגים כל 10,000 ק\"מ"},
    ],
    specs={"brake_fluid": "DOT 4 (או HZY4), 0.6-0.7 ליטר",
           "coolant": "50% גליקול + 50% מים, 11 ליטר",
           "battery": "סוללת הנעה + מצבר 12V",
           "_note": "שמן תיבת ההפחתה: Total TRANSTEC API GL-4 75W-90, 0.85 ליטר; גז מזגן R-134a 650 גרם; מנוע TZ200XSJ (150 קו\"ט). מתוך ספר הנהג העברי 2022, עמ' 254-256"},
    sources=[
        {"url": "https://skywell.co.il/wp-content/uploads/2024/09/חוברת-אחריות-מועדכנת-ל-1.9.24.pdf", "kind": "importer",
         "note": "חוברת שירות ואחריות של היבואן (עדכון 1.9.24): טבלת 'תוכנית טיפולים' עמ' 10, דפי טיפולים עמ' 11-13"},
        {"url": "https://skywell.co.il/wp-content/uploads/2022/06/Skywell-ET5-ספר-הוראות-הפעלה-לנהג.pdf", "kind": "importer",
         "note": "ספר הוראות הפעלה לנהג ET5 (2022): נוזלים ותדירות החלפה עמ' 256, סבב צמיגים עמ' 266, נתוני מנוע עמ' 254"},
        {"url": "https://skywell.co.il/wp-content/uploads/2024/03/03.24-ספר-רכב-מקוצר.pdf", "kind": "importer",
         "note": "ספר רכב מקוצר (03.24) עמ' 13: טיפול כל 24 חודשים או 40,000 ק\"מ"},
    ],
    status="reviewed",
    notes="לפי חוברת השירות והאחריות העברית של היבואן וספר הנהג. אחרי ביקורת ראשונית חינם ב-5,000 ק\"מ או חצי שנה, הטיפול חוזר כל 40,000 ק\"מ או שנתיים, ובכל טיפול מוחלפים נוזל הקירור, נוזל הבלמים, שמן תיבת ההפחתה ומסנן המזגן ונבדקים שאר הרכיבים. "
          "הטבלה מוסיפה שמסנן המזגן מוחלף בפועל כל שנה או 20,000 ק\"מ, וספר הנהג ממליץ על סבב צמיגים כל 10,000 ק\"מ. הביקורת הראשונית ב-5,000 ק\"מ אינה מופיעה ברשת הטיפולים כי אינה מתיישבת עם מרווח 40,000.",
))
