import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b=await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', proxy: { server: process.env.HTTPS_PROXY }, args: ['--ignore-certificate-errors'] });
const ctx=await b.newContext({userAgent:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36"});
const p=await ctx.newPage(); const reqs=new Set();
p.on('request', r=>{const u=r.url(); if(!/\.(png|jpe?g|svg|css|woff2?|gif|webp)(\?|$)/.test(u) && !/google|doubleclick|adsystem|gstatic|facebook|cookie/.test(u)) reqs.add(u);});
await p.goto(process.argv[2],{timeout:90000,waitUntil:'networkidle'}).catch(e=>console.log('ERR',e.message));
await p.waitForTimeout(8000);
console.log([...reqs].join('\n'));
const fr = p.frames().map(f=>f.url()); console.log('FRAMES', fr.join('\n'));
await b.close();
