import sys; sys.path.insert(0,'.')
from gen import *
IMP='כלמוביל'
ML='https://www.manualslib.com/manual/{}/x.html?page={}'
s=S('mitsubishi-l200-2006-2015-2.5-diesel','Mitsubishi','מיצובישי','L200','L200 (טריטון)','KB/KA (דור 4)',(2006,2015),['2.5 DI-D (4D56)'],'diesel',IMP,10000,12,
    'לפי טבלת "General Export" של מיצובישי לפלטפורמה זו: שמן ומסנן שמן בדיזל כל 10,000 ק"מ או 12 חודשים (בתנאים קשים כל 5,000); שאר הבדיקות כל 20,000 ק"מ או 12 חודשים',120000)
s.every('engine_oil','replace',10000); s.every('oil_filter','replace',10000)
for k in s.kms():
    for it,n in (('brake_fluid','בדיקת מפלס נוזל בלמים ומצמד'),('battery_12v',None),('pedals','חופש דוושות בלם ומצמד')): s.add(k,it,'inspect',n)
s.every('drive_belt','inspect',20000)
s.every('vacuum_hose','inspect',20000,'צינור שמן משאבת ואקום')
s.every('intercooler_pipes','inspect',40000,'צינור יניקה וצינור שמן טורבו; מעל 100,000 ק"מ צינור שמן הטורבו כל 20,000')
s.every('pcv_valve','inspect',40000,'מערכת אוורור בית ארכובה')
s.every('valve_clearance','inspect',40000,'כולל בדיקת רעש כל 20,000')
s.every('coolant_hoses','inspect',40000)
s.every('cooling_system','inspect',20000,'מפלס נוזל קירור')
s.every('coolant','replace',40000,'כל 40,000 ק"מ או שנתיים')
s.every('air_filter','inspect',20000,'בתנאי אבק כל 10,000 ק"מ או 6 חודשים')
s.every('air_filter','replace',40000)
s.every('brake_fluid','replace',40000,'כל 40,000 ק"מ או שנתיים')
s.every('fuel_filter','replace',20000,'מסנן סולר כל 20,000 ק"מ או 12 חודשים')
for it in ('suspension','propshaft','cv_boots','steering','manual_gearbox_oil','transfer_case_oil','differential_oil','exhaust','parking_brake','wheel_alignment','brake_lines','brake_pads','brake_discs','transmission_oil','diagnostics'):
    note={'propshaft':'גירוז גל ההינע','manual_gearbox_oil':'בדיקת דליפות','transfer_case_oil':'בדיקת דליפות','differential_oil':'בדיקת דליפות בדיפרנציאל קדמי ואחורי','transmission_oil':'בדיקת מפלס בגיר אוטומטי','diagnostics':'בדיקת סל"ד סרק, מערכת EGR ולימוד כמות הזרקה במערכת Common Rail; נסיעת מבחן','cv_boots':'בתנאים קשים כל 10,000'}.get(it)
    s.every(it,'inspect',20000,note)
s.add(60000,'suspension','inspect','בדיקת מרווח מיסבי גלגלים (כל 60,000 ק"מ או 3 שנים)'); s.add(120000,'suspension','inspect','בדיקת מרווח מיסבי גלגלים')
s.every('brake_drums','inspect',40000,'בלמי תוף (אם קיימים); בתנאים קשים כל 10,000')
s.every('fuel_lines','inspect',40000)
s.li('timing_belt','replace',every_km=100000,note='כולל רצועת איזון (B) במנוע 4D56')
s.li('manual_gearbox_oil','replace',every_km=100000,note='בתנאים קשים כל 40,000')
s.li('transfer_case_oil','replace',every_km=100000,note='בתנאים קשים כל 40,000')
s.li('differential_oil','replace',every_km=80000,note='דיפרנציאל רגיל; בתנאים קשים כל 40,000. בדיפרנציאל LSD היברידי כל 40,000 (קשים: 20,000)')
s.li('transmission_oil','replace',every_km=40000,note='גיר אוטומטי: בטבלת General Export מופיעה החלפה רק בתנאים קשים (כל 40,000)')
s.li('cabin_filter','replace',every_km=15000,every_months=12,note='מסנן מטהר אוויר בתא הנוסעים')
s.time('body_underside','inspect',12,'בדיקת מצב המרכב')
s.src(ML.format(1634870,31),'manufacturer','Mitsubishi Pajero Sport 2013 (KH, אותה פלטפורמה ואותו מנוע 4D56 כמו L200/Triton) Inspection and Maintenance manual, "Periodic Inspection and Maintenance Schedule - For General Export" (manualslib עמ\' 31-34); טבלת "For Europe" בעמ\' 34-37')
s.src('https://www.mitsubishi-motors.com.au/owners/service/maintenance-schedule.html','manufacturer','מיצובישי אוסטרליה מפרסמת לוחות רק לדגמים מ-2015 ואילך (Triton MQ/MR); לדור KB/MN אין לוח')
s.write('draft','טיוטה: לא נמצא לוח ישראלי ל-L200 דור 4. הלוח נבנה מטבלת "General Export" במדריך הבדיקה והתחזוקה של פג\'רו ספורט 2013, שבנוי על אותה פלטפורמה ואותו מנוע 2.5 דיזל 4D56 כמו ה-L200/טריטון. רצועת תזמון (כולל רצועת איזון) כל 100,000 ק"מ, מסנן סולר כל 20,000, נוזל קירור ונוזל בלמים כל 40,000 או שנתיים. בטבלה האירופית של אותו מסמך הטיפול הוא כל 20,000 ק"מ, ונוזל הקירור כל 60,000 או 4 שנים. הספר מגדיר נהיגה בעומס תנועה בחום מעל 32 מעלות, אבק ודרכים משובשות כתנאים קשים.')
rule('Mitsubishi',['L200','L 200','L-200'],(2006,2015),'mitsubishi-l200-2006-2015-2.5-diesel',engine_codes=['4D56'])
save_rules('rules_mit.json')
