from lib import grid, write

HY_LIB = "https://www.hyundaimotors.co.il/maintenance/"
KIA_LIB = "https://kia-israel.co.il/%d7%a7%d7%91%d7%9c-%d7%a1%d7%a4%d7%a8-%d7%a8%d7%9b%d7%91-%d7%9c%d7%9e%d7%99%d7%99%d7%9c"
KIA_DECL = {"url": "https://kia-israel.co.il/טיפול-ותחזוקה/טיפולים-לרכב", "kind": "importer",
            "note": "הצהרת קיה ישראל: טיפול תקופתי כל 15,000 ק\"מ או שנה"}

RG = "נוזל תיבת ההפחתה (ממסרה חד-הילוכית)"
EV_SPEC = {"brake_fluid": "DOT 4", "battery": "מצבר עזר 12V + סוללת מתח גבוה", "fuel": "חשמלי"}

# ---------------- Hyundai IONIQ 5, 2021 book (15,000 / 12) ----------------
write({
    "id": "hyundai-ioniq-5-2021-2023-ev",
    "make": "Hyundai", "make_he": "יונדאי", "model": "IONIQ 5", "model_he": "איוניק 5",
    "generation": "NE", "years": [2021, 2023], "engines": ["EV (EM17)"], "fuel": "electric",
    "importer": "כלמוביל",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן (2021): כל 15,000 ק\"מ או 12 חודשים, המוקדם מביניהם"},
    "cycle_km": 120000,
    "services": grid(15000, 8, [
        ("electrical_system", "IIIIIIII", "כל מערכות החשמל"),
        ("transmission_oil", "---I---I", RG),
        ("brake_lines", "IIIIIIII"),
        ("pedals", "-I-I-I-I", "דוושת בלם"),
        ("parking_brake", "-I-I-I-I"),
        ("brake_fluid", "IRIRIRIR"),
        ("brake_pads", "IIIIIIII"),
        ("brake_discs", "IIIIIIII"),
        ("steering", "IIIIIIII", "מנגנון היגוי, מוטות וגומיות"),
        ("cv_boots", "-I-I-I-I", "גלי הינע וגומיות"),
        ("tires", "IIIIIIII"),
        ("suspension", "IIIIIIII", "מפרקי המתלה הקדמי"),
        ("body_underside", "IIIIIIII", "ברגים ואומים בשלדה ובמרכב"),
        ("ac_refrigerant", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "מדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
    ]),
    "long_interval": [
        {"item": "cooling_system", "action": "inspect", "first_km": 60000, "first_months": 48, "then_every_km": 30000, "then_every_months": 24,
         "note": "בדיקה ראשונה ב-60,000 ק\"מ או 4 שנים, אחר כך כל 30,000 ק\"מ או שנתיים; מפלס נוזל הקירור - בדיקה יומית"},
        {"item": "coolant", "action": "replace", "first_km": 200000, "first_months": 120, "then_every_km": 40000, "then_every_months": 24,
         "note": "נוזל קירור רגיל: ראשונה ב-200,000 ק\"מ או 10 שנים, אחר כך כל 40,000 ק\"מ או שנתיים. לנוזל מסוג מוליכות נמוכה הספר קובע החלפה כל 60,000 ק\"מ או 36 חודשים"},
        {"item": "battery_12v", "action": "inspect", "every_km": 10000, "every_months": 6, "note": "בדיקת מצב המצבר כל 10,000 ק\"מ או חצי שנה"},
        {"item": "transmission_oil", "action": "replace", "every_km": 120000, "note": "רק בתנאי שימוש קשים (דרכים משובשות, גרירה, מונית וכו'): החלפת נוזל תיבת ההפחתה כל 120,000 ק\"מ"},
    ],
    "time_based": [{"item": "ecall_battery", "action": "replace", "months": 36, "note": "סוללת מערכת eCall (אם קיימת) - כל 3 שנים"}],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://res.cloudinary.com/colmobil/images/v1716391324/הוראות-הפעלה-לנהג-יונדאי-איוניק-5-שנת-2021-Hyundai-IONIQ-5_3664d6126/הוראות-הפעלה-לנהג-יונדאי-איוניק-5-שנת-2021-Hyundai-IONIQ-5_3664d6126.pdf",
                 "kind": "importer", "note": "ספר הנהג בעברית של כלמוביל, איוניק 5 שנת 2021 - טבלת התחזוקה בעמודי PDF 604-606"},
                {"url": HY_LIB, "kind": "importer", "note": "ספריית ספרי הרכב של יונדאי ישראל"}],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספר העברי של איוניק 5 (מהדורת 2021), בעמודות של 15,000 ק\"מ/שנה. לא נמצא ספר נפרד לשנים 2022-2023, ולכן שנים אלה שויכו לספר 2021; מהדורת 2024 עברה למרווח של 30,000 ק\"מ/שנתיים (קובץ נפרד). בדיקת מערכת הקירור, החלפת נוזל הקירור ובדיקת המצבר מופיעות בספר כמרווחים נפרדים ולכן נמצאות ב-long_interval.",
})

# ---------------- Hyundai IONIQ 5, 2024/2026 books (30,000 / 24) ----------------
write({
    "id": "hyundai-ioniq-5-2024-2026-ev",
    "make": "Hyundai", "make_he": "יונדאי", "model": "IONIQ 5", "model_he": "איוניק 5",
    "generation": "NE facelift", "years": [2024, 2026], "engines": ["EV (EM17)"], "fuel": "electric",
    "importer": "כלמוביל",
    "interval": {"km": 30000, "months": 24, "note": "לפי ספר הרכב של היבואן (2024 ו-2026): כל 30,000 ק\"מ או 24 חודשים, המוקדם מביניהם"},
    "cycle_km": 240000,
    "services": grid(30000, 8, [
        ("cooling_system", "-IIIIIII"),
        ("transmission_oil", "-I-I-I-I", RG),
        ("battery_12v", "IIIIIIII"),
        ("electrical_system", "IIIIIIII", "כל מערכות החשמל"),
        ("brake_lines", "IIIIIIII"),
        ("pedals", "IIIIIIII", "דוושת בלם"),
        ("parking_brake", "IIIIIIII"),
        ("brake_fluid", "RRRRRRRR"),
        ("brake_pads", "IIIIIIII"),
        ("brake_discs", "IIIIIIII"),
        ("steering", "IIIIIIII", "מנגנון היגוי, מוטות וגומיות"),
        ("cv_boots", "IIIIIIII", "גלי הינע וגומיות"),
        ("tires", "IIIIIIII"),
        ("suspension", "IIIIIIII", "מפרקי המתלה הקדמי"),
        ("body_underside", "IIIIIIII", "ברגים ואומים בשלדה ובמרכב"),
        ("ac_refrigerant", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "מדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "first_km": 150000, "first_months": 120, "then_every_km": 30000, "then_every_months": 24,
         "note": "בטבלה: החלפה ראשונה בטיפול 150,000 ק\"מ (120 חודשים) ומשם בכל טיפול של 30,000 ק\"מ"},
        {"item": "transmission_oil", "action": "replace", "every_km": 120000, "note": "רק בתנאי שימוש קשים: החלפת נוזל תיבת ההפחתה כל 120,000 ק\"מ"},
    ],
    "time_based": [{"item": "ecall_battery", "action": "replace", "months": 48, "note": "סוללת מערכת eCall (אם קיימת) - כל 4 שנים"}],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://res.cloudinary.com/colmobil/images/v1727073762/Hyundai_Ioniq5_OM_2024_web/Hyundai_Ioniq5_OM_2024_web.pdf",
                 "kind": "importer", "note": "ספר הנהג בעברית של כלמוביל, איוניק 5 2024 - עמודי PDF 639-642"},
                {"url": "https://res.cloudinary.com/colmobil/images/v1777980521/Hyundai_Ioniq5_OM_2026-web_3074266b03/Hyundai_Ioniq5_OM_2026-web_3074266b03.pdf",
                 "kind": "importer", "note": "ספר 2026 - עמודי PDF 649-650, טבלה זהה"},
                {"url": HY_LIB, "kind": "importer", "note": "ספריית ספרי הרכב של יונדאי ישראל"}],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספרי 2024 ו-2026 של איוניק 5 (זהות), בעמודות של 30,000 ק\"מ/שנתיים. נוזל הקירור מסומן להחלפה החל מ-150,000 ק\"מ ובכל טיפול אחריו - מופיע ב-long_interval. השיוך של 2024 כשנת המעבר לספר הזה הוא לפי שנת המהדורה.",
})

# ---------------- Hyundai KONA Electric OS, 2021 book (15,000 / 12) ----------------
write({
    "id": "hyundai-kona-electric-2021-2024-ev",
    "make": "Hyundai", "make_he": "יונדאי", "model": "KONA Electric", "model_he": "קונה חשמלית",
    "generation": "OS", "years": [2021, 2024], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "כלמוביל",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן: כל 15,000 ק\"מ או 12 חודשים, המוקדם מביניהם"},
    "cycle_km": 120000,
    "services": grid(15000, 8, [
        ("electrical_system", "IIIIIIII", "כל המערכות החשמליות"),
        ("transmission_oil", "---I---I", RG),
        ("battery_12v", "IIIIIIII"),
        ("brake_lines", "IIIIIIII"),
        ("pedals", "-I-I-I-I", "דוושת בלם"),
        ("parking_brake", "-I-I-I-I"),
        ("brake_fluid", "IRIRIRIR"),
        ("brake_pads", "IIIIIIII"),
        ("brake_discs", "IIIIIIII"),
        ("steering", "IIIIIIII", "תיבת היגוי, זרועות ושרוולים"),
        ("cv_boots", "-I-I-I-I", "גלי הינע ושרוולים"),
        ("tires", "IIIIIIII"),
        ("suspension", "IIIIIIII", "מפרקים כדוריים במתלה הקדמי"),
        ("body_underside", "IIIIIIII", "ברגים ואומים בשלדה ובמרכב"),
        ("ac_refrigerant", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "מדחס המזגן"),
        ("cabin_filter", "-R-R-R-R"),
    ]),
    "long_interval": [
        {"item": "cooling_system", "action": "inspect", "first_km": 60000, "first_months": 48, "then_every_km": 30000, "then_every_months": 24,
         "note": "בדיקה ראשונה ב-60,000 ק\"מ או 4 שנים, אחר כך כל 30,000 ק\"מ או שנתיים; מפלס ונזילות - בדיקה יומית"},
        {"item": "coolant", "action": "replace", "every_km": 60000, "every_months": 48, "note": "החלפת נוזל קירור כל 60,000 ק\"מ או 48 חודשים"},
    ],
    "time_based": [{"item": "ecall_battery", "action": "replace", "months": 36, "note": "סוללת מערכת eCall (אם קיימת) - כל 3 שנים"}],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://res.cloudinary.com/colmobil/images/v1727255817/KONA-EV-hebrew-22.08.2021-4web-L/KONA-EV-hebrew-22.08.2021-4web-L.pdf",
                 "kind": "importer", "note": "ספר הנהג בעברית של קונה חשמלית (מהדורת 08/2021) - עמודי PDF 463-464"},
                {"url": HY_LIB, "kind": "importer", "note": "ספריית ספרי הרכב של יונדאי ישראל"}],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספר העברי של קונה החשמלית מהדור הראשון (OS). בטבלה מופיעה פעמיים שורת בדיקת מערכת החשמל (פעם בכל טיפול ופעם כל 30,000 ק\"מ) - כאן נרשמה בדיקה בכל טיפול. ברישוי הדגם רשום כ-KONA עם דלק חשמל.",
})

# ---------------- Hyundai KONA Electric SX2, 2026 book (30,000 / 24) ----------------
write({
    "id": "hyundai-kona-electric-2023-2026-ev",
    "make": "Hyundai", "make_he": "יונדאי", "model": "KONA Electric", "model_he": "קונה חשמלית",
    "generation": "SX2", "years": [2023, 2026], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "כלמוביל",
    "interval": {"km": 30000, "months": 24, "note": "לפי ספר הרכב של היבואן (2026): כל 30,000 ק\"מ או 24 חודשים; בנוסף בדיקת מערכת מתח גבוה כל 12 חודשים או 13,000 ק\"מ"},
    "cycle_km": 240000,
    "services": grid(30000, 8, [
        ("cooling_system", "IIIIIIII"),
        ("coolant", "IIIIIIII", "בדיקה; החלפה ב-240,000 ק\"מ"),
        ("battery_12v", "IIIIIIII"),
        ("electrical_system", "IIIIIIII"),
        ("brake_lines", "IIIIIIII"),
        ("pedals", "IIIIIIII", "דוושת בלם"),
        ("parking_brake", "IIIIIIII"),
        ("brake_fluid", "RRRRRRRR"),
        ("brake_pads", "IIIIIIII"),
        ("brake_discs", "IIIIIIII"),
        ("steering", "IIIIIIII", "בדיקת חופשים"),
        ("cv_boots", "IIIIIIII", "בדיקת חופשים בגלי ההינע"),
        ("tires", "IIIIIIII"),
        ("suspension", "IIIIIIII", "בדיקת חופשים"),
        ("ac_refrigerant", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "מדחס המזגן"),
        ("cabin_filter", "IIIIIIII", "בדיקה והחלפה לפי הצורך"),
        ("ecall_battery", "-R-R-R-R"),
        ("hybrid_system", "IIIIIIII", "בדיקת EV special care בכל טיפול"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "every_km": 240000, "every_months": 192, "note": "בטבלה: החלפה בטיפול 240,000 ק\"מ (192 חודשים)"},
        {"item": "hybrid_system", "action": "inspect", "every_km": 13000, "every_months": 12,
         "note": "טבלה נפרדת לרכב חשמלי: כל 12 חודשים או 13,000 ק\"מ - בדיקת בידוד ומתח בסוללת המתח הגבוה, כמות נוזל הקירור, משאבת המים החשמלית והשסתום התלת-כיווני, סריקת קודי תקלה, ונזק לתחתית הסוללה ולכבלי המתח הגבוה"},
    ],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://res.cloudinary.com/colmobil/images/v1782197556/KONA-EV2026-all-web-low/KONA-EV2026-all-web-low.pdf",
                 "kind": "importer", "note": "ספר הנהג בעברית של קונה EV 2026 - לוח תחזוקה רגילה ולוח טיפול מיוחד לרכב חשמלי, עמודי PDF 497-498 (סרוקים)"},
                {"url": HY_LIB, "kind": "importer", "note": "ספריית ספרי הרכב של יונדאי ישראל"}],
    "status": "reviewed",
    "notes": "הועתק מהטבלאות הסרוקות בספר העברי של קונה EV 2026 (דור שני). הטבלה של הספר כוללת גם זמן עבודה לכל טיפול (2.4 שעות, 2.9 בטיפול 240,000). בספר זה אין שורה לנוזל תיבת ההפחתה. השנים 2023-2025 שויכו לספר 2026 כי זה הספר היחיד לדור השני באתר היבואן; ברישוי הדגם רשום כ-KONA EV.",
})

# ---------------- Kia EV6 (30,000 / 24) ----------------
write({
    "id": "kia-ev6-2022-2024-ev",
    "make": "Kia", "make_he": "קיה", "model": "EV6", "model_he": "EV6",
    "generation": "CV", "years": [2022, 2024], "engines": ["EV (EM17 / EM07:EM17)"], "fuel": "electric",
    "importer": "טלקאר",
    "interval": {"km": 30000, "months": 24, "note": "לפי ספר הרכב של היבואן: כל 30,000 ק\"מ או 24 חודשים, המוקדם מביניהם"},
    "cycle_km": 240000,
    "services": grid(30000, 8, [
        ("transmission_oil", "-I-I-I-I", RG),
        ("cv_boots", "IIIIIIII", "גלי הינע ושרוולים"),
        ("cooling_system", "-IIIIIII"),
        ("ac_system", "IIIIIIII", "קרר ומדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
        ("brake_pads", "IIIIIIII"),
        ("brake_discs", "IIIIIIII"),
        ("brake_lines", "IIIIIIII"),
        ("brake_fluid", "RRRRRRRR"),
        ("steering", "IIIIIIII", "מסרק, חיבורים ושרוולים"),
        ("suspension", "IIIIIIII", "מפרקים כדוריים"),
        ("tires", "IIIIIIII"),
        ("battery_12v", "IIIIIIII"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "first_km": 210000, "first_months": 120, "then_every_km": 30000, "then_every_months": 24,
         "note": "ראשונה ב-210,000 ק\"מ או 120 חודשים, אחר כך כל 30,000 ק\"מ או 24 חודשים"},
        {"item": "transmission_oil", "action": "replace", "every_km": 120000, "note": "רק בתנאי שימוש קשים: החלפת נוזל תיבת ההפחתה כל 120,000 ק\"מ"},
    ],
    "time_based": [{"item": "ecall_battery", "action": "replace", "months": 48, "note": "סוללת eCall (אם קיימת) - כל 4 שנים"}],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://cdnmedia.kia-israel.co.il/www/cars-book/KIA_EV6_OM_2022.pdf", "kind": "importer",
                 "note": "ספר הרכב בעברית של קיה EV6 2022 (טלקאר) - עמודי PDF 430-431"},
                {"url": KIA_LIB, "kind": "importer", "note": "עמוד ספרי הרכב של קיה ישראל"}],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספר העברי של EV6, בעמודות של 30,000 ק\"מ/שנתיים. מפלס נוזל הקירור ונזילות - בדיקה יומית לפי ההערה בספר.",
})

NIRO_ROWS_15 = lambda brake_fluid, cabin, discs: [
    ("transmission_oil", "---I---I", RG),
    ("cv_boots", "-I-I-I-I", "גלי הינע ושרוולים"),
    ("ac_system", "IIIIIIII", "קרר ומדחס המזגן"),
    ("cabin_filter", cabin),
    ("brake_pads", discs),
    ("brake_discs", discs),
    ("brake_lines", discs),
    ("brake_fluid", brake_fluid),
    ("steering", "IIIIIIII", "מסרק, חיבורים ושרוולים"),
    ("suspension", "IIIIIIII", "מפרקים כדוריים"),
    ("tires", "IIIIIIII"),
    ("battery_12v", "IIIIIIII"),
]

# ---------------- Kia Niro EV DE, 2021 book ----------------
rows = NIRO_ROWS_15("IRIRIRIR", "-R-R-R-R", "IIIIIIII")
rows.insert(5, ("pedals", "-I-I-I-I", "דוושת בלם"))
write({
    "id": "kia-niro-ev-2021-2022-ev",
    "make": "Kia", "make_he": "קיה", "model": "Niro EV", "model_he": "נירו EV",
    "generation": "DE", "years": [2021, 2022], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "טלקאר",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן: כל 15,000 ק\"מ או 12 חודשים, המוקדם מביניהם"},
    "cycle_km": 120000,
    "services": grid(15000, 8, rows),
    "long_interval": [
        {"item": "coolant", "action": "replace", "every_km": 60000, "every_months": 36, "note": "כל 60,000 ק\"מ או 36 חודשים"},
        {"item": "cooling_system", "action": "inspect", "first_km": 60000, "first_months": 48, "then_every_km": 30000, "then_every_months": 24,
         "note": "בדיקה ראשונה ב-60,000 ק\"מ או 48 חודשים, אחר כך כל 30,000 ק\"מ או 24 חודשים"},
    ],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://cdnmedia.kia-israel.co.il/www/cars-book/KIA-Niro-EV-OM-2021.pdf", "kind": "importer",
                 "note": "ספר הרכב בעברית של נירו EV 2021 - עמודי PDF 470-471"},
                {"url": KIA_LIB, "kind": "importer", "note": "עמוד ספרי הרכב של קיה ישראל"}, KIA_DECL],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספר העברי של נירו EV מהדור הראשון (DE), בעמודות של 15,000 ק\"מ/שנה. השנים 2023-2024 שייכות לדור החדש (ספר 2023, קובץ נפרד) - החלוקה לפי שנת הדגם משוערת.",
})

# ---------------- Kia Niro EV SG2, 2023 book (non-Europe table) ----------------
write({
    "id": "kia-niro-ev-2023-2024-ev",
    "make": "Kia", "make_he": "קיה", "model": "Niro EV", "model_he": "נירו EV",
    "generation": "SG2", "years": [2023, 2024], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "טלקאר",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן (טבלת 'למעט אירופה'): כל 15,000 ק\"מ או 12 חודשים"},
    "cycle_km": 120000,
    "services": grid(15000, 8, [
        ("transmission_oil", "---I---I", RG),
        ("cv_boots", "-I-I-I-I", "גלי הינע ושרוולים"),
        ("cooling_system", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "קרר ומדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
        ("brake_pads", "-I-I-I-I"),
        ("brake_discs", "-I-I-I-I"),
        ("brake_lines", "-I-I-I-I"),
        ("brake_fluid", "IIRIIRII"),
        ("steering", "IIIIIIII", "מסרק, מוט קישור וגומיות"),
        ("suspension", "IIIIIIII", "מפרקים כדוריים"),
        ("tires", "IIIIIIII"),
        ("battery_12v", "IIIIIIII"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "first_km": 180000, "first_months": 120, "then_every_km": 30000, "then_every_months": 24,
         "note": "ראשונה ב-180,000 ק\"מ או 120 חודשים, אחר כך כל 30,000 ק\"מ או 24 חודשים"},
        {"item": "brake_fluid", "action": "replace", "every_km": 45000, "every_months": 36, "note": "בטבלה (שורת 'חוץ מאוסטרליה וניו-זילנד'): החלפה ב-45,000 וב-90,000 ק\"מ"},
    ],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://cdnmedia.kia-israel.co.il/www/cars-book/NIRO_Hebrew_01_%D7%97%D7%A9%D7%9E%D7%9C%D7%99_2023.pdf", "kind": "importer",
                 "note": "ספר הרכב בעברית של נירו חשמלי 2023 - עמודי PDF 432-433 (שתי טבלאות: אירופה, ולמעט אירופה)"},
                {"url": KIA_LIB, "kind": "importer", "note": "עמוד ספרי הרכב של קיה ישראל"}, KIA_DECL],
    "status": "reviewed",
    "notes": "בספר שתי טבלאות: לאירופה (30,000 ק\"מ/שנתיים) ולמעט אירופה (15,000 ק\"מ/שנה). נבחרה הטבלה שלמעט אירופה כי קיה ישראל מצהירה על טיפול כל 15,000 ק\"מ או שנה, ובשורות המפוצלות נלקחה האפשרות 'חוץ מאוסטרליה וניו-זילנד'.",
})

# ---------------- Kia Niro Plus EV ----------------
write({
    "id": "kia-niro-plus-ev-2022-2024-ev",
    "make": "Kia", "make_he": "קיה", "model": "Niro Plus EV", "model_he": "נירו פלוס חשמלי",
    "generation": "DE (Niro Plus)", "years": [2022, 2024], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "טלקאר",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן: כל 15,000 ק\"מ או 12 חודשים, המוקדם מביניהם"},
    "cycle_km": 120000,
    "services": grid(15000, 8, [
        ("transmission_oil", "---I---I", RG),
        ("cv_boots", "-I-I-I-I", "גלי הינע ושרוולים"),
        ("cooling_system", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "קרר ומדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
        ("brake_pads", "-I-I-I-I"),
        ("brake_discs", "-I-I-I-I"),
        ("brake_lines", "-I-I-I-I"),
        ("brake_fluid", "IIRIIRII"),
        ("steering", "IIIIIIII", "מסרק, חיבורים ושרוולים"),
        ("suspension", "IIIIIIII", "מפרקים כדוריים"),
        ("tires", "IIIIIIII"),
        ("battery_12v", "IIIIIIII"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "every_km": 60000, "every_months": 36, "note": "כל 60,000 ק\"מ או 36 חודשים"},
        {"item": "brake_fluid", "action": "replace", "every_km": 45000, "every_months": 36, "note": "בטבלה: החלפה ב-45,000 וב-90,000 ק\"מ"},
    ],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://cdnmedia.kia-israel.co.il/www/cars-book/Niro-Plus-DE-PV-EV-2023.pdf", "kind": "importer",
                 "note": "ספר הרכב בעברית של נירו פלוס חשמלי - עמוד PDF 318"},
                {"url": KIA_LIB, "kind": "importer", "note": "עמוד ספרי הרכב של קיה ישראל"}, KIA_DECL],
    "status": "reviewed",
    "notes": "הועתק מטבלת התחזוקה הרגילה בספר העברי של נירו פלוס החשמלי, בעמודות של 15,000 ק\"מ/שנה. נוזל הבלמים מוחלף לפי הטבלה בכל 45,000 ק\"מ.",
})

# ---------------- Kia EV3 (non-Europe table) ----------------
write({
    "id": "kia-ev3-2025-2026-ev",
    "make": "Kia", "make_he": "קיה", "model": "EV3", "model_he": "EV3",
    "generation": "SV1", "years": [2025, 2026], "engines": ["EV (EM16)"], "fuel": "electric",
    "importer": "טלקאר",
    "interval": {"km": 15000, "months": 12, "note": "לפי ספר הרכב של היבואן (טבלת 'חוץ מאשר אירופה'): כל 15,000 ק\"מ או 12 חודשים"},
    "cycle_km": 120000,
    "services": grid(15000, 8, [
        ("transmission_oil", "---I---I", RG),
        ("cv_boots", "-I-I-I-I", "גלי הינע וגומיות"),
        ("cooling_system", "IIIIIIII"),
        ("ac_system", "IIIIIIII", "קרר ומדחס המזגן"),
        ("cabin_filter", "RRRRRRRR"),
        ("brake_pads", "-I-I-I-I"),
        ("brake_discs", "-I-I-I-I"),
        ("brake_lines", "-I-I-I-I"),
        ("brake_fluid", "IIRIIRII"),
        ("steering", "IIIIIIII", "מסרק, מוט קישור וגומיות"),
        ("suspension", "IIIIIIII", "מפרקים כדוריים"),
        ("tires", "IIIIIIII"),
        ("battery_12v", "IIIIIIII"),
    ]),
    "long_interval": [
        {"item": "coolant", "action": "replace", "first_km": 180000, "first_months": 120, "then_every_km": 30000, "then_every_months": 24,
         "note": "ראשונה ב-180,000 ק\"מ או 120 חודשים, אחר כך כל 30,000 ק\"מ או 24 חודשים"},
        {"item": "brake_fluid", "action": "replace", "every_km": 45000, "every_months": 36, "note": "בטבלה (שורת 'למעט אוסטרליה וניו-זילנד'): החלפה ב-45,000 וב-90,000 ק\"מ"},
    ],
    "time_based": [{"item": "ecall_battery", "action": "replace", "months": 48, "note": "סוללת eCall (אם קיימת) - כל 4 שנים"}],
    "specs": dict(EV_SPEC, _note="לפי ספר הרכב של היבואן"),
    "sources": [{"url": "https://cdnmedia.kia-israel.co.il/www/cars-book/EV3_Book.pdf", "kind": "importer",
                 "note": "ספר הרכב בעברית של EV3 - עמודי PDF 644-645"},
                {"url": KIA_LIB, "kind": "importer", "note": "עמוד ספרי הרכב של קיה ישראל"}, KIA_DECL],
    "status": "reviewed",
    "notes": "בספר שתי טבלאות: רגילה (30,000 ק\"מ/שנתיים) ו'חוץ מאשר אירופה' (15,000 ק\"מ/שנה). נבחרה השנייה לפי הצהרת קיה ישראל על טיפול כל 15,000 ק\"מ או שנה, ובשורות המפוצלות האפשרות שאינה לאוסטרליה וניו-זילנד. אחרי טבילה במים יש להחליף את נוזל תיבת ההפחתה.",
})
