import sys; sys.path.insert(0,'.')
from gen import *
IMP='טלקאר'
URL='https://www.manua.ls/daihatsu/terios-2009/manual?p=236'
s=S('daihatsu-terios-2006-2011-1.5','Daihatsu','דייהטסו','Terios','טריוס','J200',(2006,2011),['1.5 (3SZ-VE)'],'petrol',IMP,
    15000,12,'לפי "תוכנית תחזוקה לשימוש רגיל" בספר הבעלים האירופי: טיפול כל 15,000 ק"מ או שנה, המוקדם; בשימוש קשה שמן ומסנן כל 7,500 ק"מ או חצי שנה',90000)
s.every('engine_oil','replace',15000,'שמן API SH ומעלה; עם שמן API SG כל 12,000 ק"מ או שנה')
s.every('oil_filter','replace',15000)
s.pat('air_filter','IIRIIR',15000,'ניקוי ובדיקה; החלפה כל 45,000 ק"מ')
s.pat('fuel_lines','-I-I-I',15000,'צנרת וחיבורי דלק כולל פתח המילוי')
s.every('drive_belt','inspect',15000,'רצועת אלטרנטור, משאבת מים, מזגן והגה כוח')
s.pat('spark_plugs','-I-I-I',15000,'מצתים רגילים: ניקוי ובדיקה (מצתי אירידיום מוחלפים כל 90,000 ק"מ)')
s.pat('evap_system','--I--I',15000,'מיכל פחם פעיל')
s.pat('exhaust','-I-I-I',15000)
s.every('clutch','inspect',15000,'חופש דוושת המצמד ומרחק שמורה')
s.pat('manual_gearbox_oil','-I-I-R',15000,'גיר ידני')
s.pat('transmission_oil','--I--R',15000,'גיר אוטומטי, כולל בדיקת צינורות מצנן השמן של הגיר')
s.pat('transfer_case_oil','-I-I-R',15000,'דיפרנציאל מרכזי (הנעה כפולה)')
s.pat('differential_oil','-R-R-R',15000,'דיפרנציאל קדמי ואחורי')
s.pat('propshaft','-I-I-I',15000,'גל הינע: הידוק, רעידות ונזקים')
s.pat('cv_boots','-I-I-I',15000)
s.pat('suspension','-I-I-I',15000,'זרועות, קפיצים, מוט מייצב וכיסויי אבק')
s.pat('steering','-I-I-I',15000,'מפרקים, תיבת הגה וכיסויי אבק')
s.pat('wheel_alignment','--I--I',15000)
s.pat('pedals','-I-I-I',15000,'דוושת בלם ובלם יד')
s.pat('parking_brake','-I-I-I',15000)
s.every('brake_pads','inspect',15000,'דיסקים ורפידות')
s.every('brake_discs','inspect',15000)
s.pat('brake_lines','-I-I-I',15000,'צנרת בלמים, שסתומי ויסות ומשאבת הבלמים (דליפות)')
s.pat('brake_drums','-I-I-I',15000)
s.every('body_underside','inspect',15000,'הידוק ברגים, טבורי גלגלים ושלדה')
s.li('spark_plugs','replace',every_km=90000,note='מצתי אירידיום')
s.time('coolant','replace',24,'נוזל קירור לאורך חיים: כל שנתיים')
s.time('brake_fluid','replace',24,'כל שנתיים')
s.time('clutch','replace',24,'החלפת נוזל המצמד כל שנתיים')
s.time('evap_system','replace',96,'צינורות אדי דלק: החלפה כל 8 שנים')
s.src(URL,'manufacturer','Daihatsu Terios owner\'s manual (אירופה, מהדורה איטלקית 2009), פרק 13 "Programma di manutenzione", עמודים 13-3 עד 13-7 (manua.ls p.236-240): לוח לשימוש רגיל ולשימוש קשה')
s.src('https://procarmanuals.com/category/manual/daihatsu-manual/','other','בקטגוריית דייהטסו ב-procarmanuals יש רק ספרי שירות של טריוס J100 ושל מטריה, בלי לוח לדור J200')
notes=('לא נמצא ספר עברי של טלקאר לטריוס. הלוח לקוח מספר הבעלים האירופי (מהדורה איטלקית, 2009) של טריוס עם מנוע 1.5. '
       'המחזור בטבלה הוא 90,000 ק"מ או 6 שנים וחוזר על עצמו. נוזל קירור, נוזל בלמים ונוזל מצמד מוחלפים כל שנתיים בלי קשר לק"מ. '
       'שורות הדיפרנציאל המרכזי ושמן הדיפרנציאלים נוגעות לגרסאות הנעה כפולה. בטבלה אין שורת בדיקת שסתומים או רצועת תזמון. '
       'בשימוש קשה (גרירה, נסיעות קצרות, דרכים משובשות או מאובקות) שמן ומסנן כל 7,500 ק"מ, בדיקת מסנן אוויר כל 5,000 ק"מ והחלפתו כל 15,000, ונוזל גיר אוטומטי ב-45,000 ק"מ.')
s.write('draft',notes)
rule('Daihatsu',['TERIOS'],(2006,2012),'daihatsu-terios-2006-2011-1.5',engine_codes=['3SZ'])
save_rules('rules_daihatsu.json')
